// Magenta '67 service worker (generated by build.py from tools/sw_template.js; v14.8).
// Keeps this build's whole game on the device so the installed app (or a revisit) runs with no internet:
//  - install: every file of the build is saved in the cache 'm67-<build>' (one failed file doesn't stop the rest)
//  - the page: network first (so a new version shows as soon as you're online; 4 s at most), the saved copy offline
//  - everything else on this site: the saved copy first, else the network (and saved for next time)
//  - other sites (online play's server, anything else): left alone
//  - a new build = a new sw.js = a new cache; the old one is deleted once the new one is ready
const BUILD = '94870e5a2e-5c1b63f5';
const CACHE = 'm67-' + BUILD;
const PRECACHE = [
 "./",
 "apple-touch-icon.png",
 "assets/bld_barn_map.webp",
 "assets/bld_barn_orm.webp",
 "assets/bld_barn_win.webp",
 "assets/bld_church_map.webp",
 "assets/bld_church_orm.webp",
 "assets/bld_church_win.webp",
 "assets/bld_cinema_map.webp",
 "assets/bld_cinema_orm.webp",
 "assets/bld_cinema_win.webp",
 "assets/bld_desertgas_map.webp",
 "assets/bld_desertgas_orm.webp",
 "assets/bld_diner_map.webp",
 "assets/bld_diner_orm.webp",
 "assets/bld_diner_win.webp",
 "assets/bld_garage_map.webp",
 "assets/bld_garage_orm.webp",
 "assets/bld_garage_win.webp",
 "assets/bld_house_a_map.webp",
 "assets/bld_house_a_orm.webp",
 "assets/bld_house_a_win.webp",
 "assets/bld_house_b_map.webp",
 "assets/bld_house_b_orm.webp",
 "assets/bld_house_b_win.webp",
 "assets/bld_lighthouse_map.webp",
 "assets/bld_lighthouse_orm.webp",
 "assets/bld_lighthouse_win.webp",
 "assets/bld_lodge_map.webp",
 "assets/bld_lodge_orm.webp",
 "assets/bld_motel_map.webp",
 "assets/bld_motel_orm.webp",
 "assets/bld_motel_win.webp",
 "assets/bld_shop_a_map.webp",
 "assets/bld_shop_a_orm.webp",
 "assets/bld_shop_a_win.webp",
 "assets/bld_shop_b_map.webp",
 "assets/bld_shop_b_orm.webp",
 "assets/bld_shop_b_win.webp",
 "assets/carhq_map.webp",
 "assets/carhq_mask.webp",
 "assets/carhq_nrm.webp",
 "assets/carhq_orm.webp",
 "assets/det_ash.webp",
 "assets/det_asphalt.webp",
 "assets/det_dirt.webp",
 "assets/det_forest.webp",
 "assets/det_grass.webp",
 "assets/det_mud.webp",
 "assets/det_rock.webp",
 "assets/det_sand.webp",
 "assets/det_snow.webp",
 "assets/fonts/archivo-latin-ext-standard-normal.woff2",
 "assets/fonts/archivo-latin-standard-normal.woff2",
 "assets/fonts/shrikhand-latin-400-normal.woff2",
 "assets/fonts/shrikhand-latin-ext-400-normal.woff2",
 "assets/moon_albedo.jpg",
 "assets/moon_height.jpg",
 "assets/peerjs.min.js",
 "assets/rival.json?v=e08d6bfe",
 "assets/rival_longnose_map.webp",
 "assets/rival_longnose_mask.webp",
 "assets/rival_longnose_nrm.webp",
 "assets/rival_longnose_orm.webp",
 "assets/rival_muscle_map.webp",
 "assets/rival_muscle_mask.webp",
 "assets/rival_muscle_nrm.webp",
 "assets/rival_muscle_orm.webp",
 "assets/rival_nova_map.webp",
 "assets/rival_nova_mask.webp",
 "assets/rival_nova_nrm.webp",
 "assets/rival_nova_orm.webp",
 "assets/rival_sting_map.webp",
 "assets/rival_sting_mask.webp",
 "assets/rival_sting_nrm.webp",
 "assets/rival_sting_orm.webp",
 "assets/three.module.min.js",
 "favicon.png",
 "game.js?v=94870e5a2e",
 "icon-192.png",
 "icon-512.png",
 "icon-maskable-512.png",
 "manifest.webmanifest",
 "sfx/backfire.mp3",
 "sfx/birds.mp3",
 "sfx/camera.mp3",
 "sfx/checkpoint.mp3",
 "sfx/cheer.mp3",
 "sfx/crash_heavy.mp3",
 "sfx/crash_light.mp3",
 "sfx/engine_high_off.mp3",
 "sfx/engine_high_on.mp3",
 "sfx/engine_idle.mp3",
 "sfx/engine_low_on.mp3",
 "sfx/engine_mid_off.mp3",
 "sfx/engine_mid_on.mp3",
 "sfx/engine_top_on.mp3",
 "sfx/gravel.mp3",
 "sfx/gulls.mp3",
 "sfx/horn.mp3",
 "sfx/land.mp3",
 "sfx/music_race.mp3",
 "sfx/music_title.mp3",
 "sfx/nos_ignite.mp3",
 "sfx/nos_loop.mp3",
 "sfx/orb_hum.mp3",
 "sfx/orb_transform.mp3",
 "sfx/pickup.mp3",
 "sfx/rain.mp3",
 "sfx/shift.mp3",
 "sfx/surf.mp3",
 "sfx/thunder.mp3",
 "sfx/turbo_bov.mp3",
 "sfx/turbo_spool.mp3",
 "sfx/tyre_squeal.mp3",
 "sfx/vo_champion.mp3",
 "sfx/vo_first.mp3",
 "sfx/vo_fourth.mp3",
 "sfx/vo_record.mp3",
 "sfx/vo_second.mp3",
 "sfx/vo_third.mp3",
 "sfx/wind.mp3"
];

self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(PRECACHE.map((u) => c.add(new Request(u, { cache: 'reload' })).catch(() => { })))));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('m67-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('message', (e) => {
  if (e.data === 'm67-cache-status') caches.open(CACHE).then((c) => c.keys()).then((ks) => e.source && e.source.postMessage({ t: 'm67-cache', build: BUILD, have: ks.length, want: PRECACHE.length }));
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const root = new URL('./', self.registration.scope).pathname;
  if (req.mode === 'navigate' && (url.pathname === root || url.pathname === root + 'index.html')) {   // (the game's page only: not e.g. preview.jpg opened on its own)
    e.respondWith((async () => {
      const c = await caches.open(CACHE);
      try {
        const net = await Promise.race([fetch(req), new Promise((_, rej) => setTimeout(() => rej(new Error('slow network')), 4000))]);
        if (net.ok) c.put('./', net.clone());
        return net;
      } catch (err) {
        return (await c.match('./')) || (await caches.match('./')) || Response.error();
      }
    })());
    return;
  }
  e.respondWith((async () => {
    const c = await caches.open(CACHE);
    const hit = await c.match(req);
    if (hit) return hit;
    try {
      const r = await fetch(req);
      if (r.status === 200) c.put(req, r.clone());
      return r;
    } catch (err) {
      const loose = await caches.match(req, { ignoreSearch: true });
      if (loose) return loose;
      throw err;
    }
  })());
});
